name: scrolling
description: A new Flutter project.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.8.1
  path_provider: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.2
  test: any

flutter:
  uses-material-design: true
