name: code_excerpter
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  build: ^2.4.1
  logging: ^1.2.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  build_runner: ^2.4.8
  test: ^1.25.2
