name: flutter_site
description: Dart-based tools for building docs.flutter.dev.
publish_to: none

environment:
  sdk: ^3.6.0-0

dependencies:
  args: ^2.4.2
  excerpter:
    path: ../../site-shared/pkgs/excerpter
  io: ^1.0.4
  linkcheck: ^3.0.0
  path: ^1.9.0

dev_dependencies:
  analysis_defaults:
    path: ../../site-shared/pkgs/analysis_defaults
