name: todo_data_service
description: Example for key_value_data cookbook recipe

resolution: workspace
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path: ^1.9.0
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true