name: flutter_io_examples

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  path: ^1.5.0
  url_launcher: ^6.1.4
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  transparent_image: ^2.0.0
  css_colors: ^1.0.2
  web_socket_channel: ^2.2.0
  sqflite: ^2.0.2+1
  camera: ^0.9.8+1
  video_player: ^2.4.5
