name: flutter_io_examples

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test: ^1.0.0
  path: ^1.5.0
  test: '<2.0.0'
  url_launcher: ^3.0.3
  path_provider: ^0.4.1
  shared_preferences: ^0.4.1
  transparent_image: ^0.1.0
  css_colors: ^1.0.2
  web_socket_channel: ^1.0.9
  sqflite: ^1.1.0
  camera: ^0.4.0+3
  video_player: ^0.10.0+2
