name: web_sockets
description: Web Sockets

environment:
  sdk: ^3.6.0-0

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.3

dev_dependencies:
  example_utils:
    path: ../../../example_utils

flutter:
  uses-material-design: true
