name: web_sockets
description: Web Sockets

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.1.0

dev_dependencies:
  example_utils:
    path: ../../../example_utils

flutter:
  uses-material-design: true
