# See Dependabot documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/animation/animate0"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/animation/animate1"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/animation/animate2"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/animation/animate3"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/animation/animate4"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/animation/animate5"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/_animation/basic_hero_animation"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/_animation/basic_radial_hero_animation"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/_animation/basic_staggered_animation"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/animation/explicit"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/_animation/hero_animation"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/animation/implicit"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/_animation/radial_hero_animation"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/_animation/radial_hero_animation_animate_rectclip"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/_animation/staggered_pic_selection"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/basics"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/animation/animated_container"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/animation/opacity_animation"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/animation/page_route_animation"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/animation/physics_simulation"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/design/drawer"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/design/fonts"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/design/orientation"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/design/package_fonts"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/design/snackbars"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/design/tabs"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/design/themes"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/effects/download_button"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/effects/drag_a_widget"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/effects/expandable_fab"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/effects/gradient_bubbles"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/effects/nested_nav"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/effects/parallax_scrolling"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/effects/photo_filter_carousel"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/effects/shimmer_loading"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/effects/staggered_menu_animation"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/effects/typing_indicator"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/forms/focus"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/forms/retrieve_input"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/forms/text_field_changes"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/forms/text_input"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/forms/validation"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/gestures/dismissible"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/gestures/handling_taps"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/gestures/ripples"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/images/cached_images"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/images/fading_in_images"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/images/network_image"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/lists/basic_list"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/lists/floating_app_bar"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/lists/grid_lists"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/lists/horizontal_list"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/lists/long_lists"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/lists/mixed_list"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/maintenance/error_reporting"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/navigation/hero_animations"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/navigation/named_routes"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/navigation/navigate_with_arguments"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/navigation/navigation_basics"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/navigation/passing_data"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/navigation/returning_data"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/networking/authenticated_requests"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/networking/background_parsing"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/networking/delete_data"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/networking/fetch_data"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/networking/send_data"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/networking/update_data"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/networking/web_sockets"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/persistence/key_value"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/persistence/reading_writing_files"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/persistence/sqlite"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/plugins/picture_using_camera"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/plugins/play_video"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/testing/integration/introduction"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/testing/integration/profiling"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/testing/unit/counter_app"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/testing/unit/mocking"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/testing/widget/finders"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/testing/widget/introduction"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/testing/widget/scrolling"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/cookbook/testing/widget/tap_drag"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/deployment/obfuscate"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/development/data-and-backend/json"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/development/platform_integration"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/development/plugin_api_migration"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/development/tools"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/development/ui/interactive"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/googleapis"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/integration_test"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/integration_test_migration"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/internationalization/add_language"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/internationalization/gen_l10n_example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/internationalization/intl_example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/internationalization/minimal"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/base"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/card_and_stack"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/constraints"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/container"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/grid_and_list"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/lakes/interactive"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/lakes/step2"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/lakes/step3"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/lakes/step4"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/lakes/step5"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/lakes/step6"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/non_material"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/pavlova"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/row_column"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/layout/sizing"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/resources/architectural_overview"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/state_mgmt/simple"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/testing/code_debugging"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/testing/common_errors"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/testing/debugging"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/testing/errors"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/testing/integration_tests/how_to"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/ui/advanced/actions_and_shortcuts"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/ui/advanced/focus"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/ui/assets_and_images"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/ui/layout/adaptive_app_demos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/ui/widgets_intro"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/visual_debugging"
    schedule:
      interval: "daily"
