# See Dependabot documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "auto.dependencies"
      - "auto.github-action"
      - "lang.yaml"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directories:
      - "/"
      - "/tool/dash_site"
    schedule:
      interval: "daily"
    labels:
      - "auto.dependencies"
      - "lang.dart"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    schedule:
      interval: "daily"
    labels:
      - "auto.code-examples"
      - "lang.dart"
    directories:
      - "/examples/_animation/basic_hero_animation"
      - "/examples/_animation/basic_radial_hero_animation"
      - "/examples/_animation/basic_staggered_animation"
      - "/examples/_animation/hero_animation"
      - "/examples/_animation/radial_hero_animation"
      - "/examples/_animation/radial_hero_animation_animate_rectclip"
      - "/examples/_animation/staggered_pic_selection"
      - "/examples/animation/animate0"
      - "/examples/animation/animate1"
      - "/examples/animation/animate2"
      - "/examples/animation/animate3"
      - "/examples/animation/animate4"
      - "/examples/animation/animate5"
      - "/examples/cookbook/animation/animated_container"
      - "/examples/cookbook/animation/opacity_animation"
      - "/examples/cookbook/animation/page_route_animation"
      - "/examples/cookbook/animation/physics_simulation"
      - "/examples/cookbook/design/drawer"
      - "/examples/cookbook/design/fonts"
      - "/examples/cookbook/design/orientation"
      - "/examples/cookbook/design/package_fonts"
      - "/examples/cookbook/design/snackbars"
      - "/examples/cookbook/design/tabs"
      - "/examples/cookbook/design/themes"
      - "/examples/cookbook/effects/download_button"
      - "/examples/cookbook/effects/drag_a_widget"
      - "/examples/cookbook/effects/expandable_fab"
      - "/examples/cookbook/effects/gradient_bubbles"
      - "/examples/cookbook/effects/nested_nav"
      - "/examples/cookbook/effects/parallax_scrolling"
      - "/examples/cookbook/effects/photo_filter_carousel"
      - "/examples/cookbook/effects/shimmer_loading"
      - "/examples/cookbook/effects/staggered_menu_animation"
      - "/examples/cookbook/effects/typing_indicator"
      - "/examples/cookbook/forms/focus"
      - "/examples/cookbook/forms/retrieve_input"
      - "/examples/cookbook/forms/text_field_changes"
      - "/examples/cookbook/forms/text_input"
      - "/examples/cookbook/forms/validation"
      - "/examples/cookbook/games/achievements_leaderboards"
      - "/examples/cookbook/games/firestore_multiplayer"
      - "/examples/cookbook/gestures/dismissible"
      - "/examples/cookbook/gestures/handling_taps"
      - "/examples/cookbook/gestures/ripples"
      - "/examples/cookbook/images/cached_images"
      - "/examples/cookbook/images/fading_in_images"
      - "/examples/cookbook/images/network_image"
      - "/examples/cookbook/lists/basic_list"
      - "/examples/cookbook/lists/floating_app_bar"
      - "/examples/cookbook/lists/grid_lists"
      - "/examples/cookbook/lists/horizontal_list"
      - "/examples/cookbook/lists/long_lists"
      - "/examples/cookbook/lists/mixed_list"
      - "/examples/cookbook/lists/spaced_items"
      - "/examples/cookbook/maintenance/error_reporting"
      - "/examples/cookbook/navigation/hero_animations"
      - "/examples/cookbook/navigation/named_routes"
      - "/examples/cookbook/navigation/navigate_with_arguments"
      - "/examples/cookbook/navigation/navigation_basics"
      - "/examples/cookbook/navigation/passing_data"
      - "/examples/cookbook/navigation/returning_data"
      - "/examples/cookbook/networking/authenticated_requests"
      - "/examples/cookbook/networking/background_parsing"
      - "/examples/cookbook/networking/delete_data"
      - "/examples/cookbook/networking/fetch_data"
      - "/examples/cookbook/networking/send_data"
      - "/examples/cookbook/networking/update_data"
      - "/examples/cookbook/networking/web_sockets"
      - "/examples/cookbook/persistence/key_value"
      - "/examples/cookbook/persistence/reading_writing_files"
      - "/examples/cookbook/persistence/sqlite"
      - "/examples/cookbook/plugins/google_mobile_ads"
      - "/examples/cookbook/plugins/picture_using_camera"
      - "/examples/cookbook/plugins/play_video"
      - "/examples/cookbook/testing/integration/introduction"
      - "/examples/cookbook/testing/integration/profiling"
      - "/examples/cookbook/testing/unit/counter_app"
      - "/examples/cookbook/testing/unit/mocking"
      - "/examples/cookbook/testing/widget/finders"
      - "/examples/cookbook/testing/widget/introduction"
      - "/examples/cookbook/testing/widget/scrolling"
      - "/examples/cookbook/testing/widget/tap_drag"
      - "/examples/data-and-backend/json"
      - "/examples/deployment/obfuscate"
      - "/examples/example_utils"
      - "/examples/get-started/flutter-for/android_devs"
      - "/examples/get-started/flutter-for/declarative"
      - "/examples/get-started/flutter-for/ios_devs"
      - "/examples/get-started/flutter-for/react_native_devs"
      - "/examples/get-started/flutter-for/react_native_devs/my_widgets"
      - "/examples/get-started/flutter-for/web_devs"
      - "/examples/get-started/flutter-for/xamarin_devs"
      - "/examples/googleapis"
      - "/examples/integration_test"
      - "/examples/integration_test_migration"
      - "/examples/internationalization/add_language"
      - "/examples/internationalization/gen_l10n_example"
      - "/examples/internationalization/intl_example"
      - "/examples/internationalization/minimal"
      - "/examples/layout/base"
      - "/examples/layout/card_and_stack"
      - "/examples/layout/constraints"
      - "/examples/layout/container"
      - "/examples/layout/gallery"
      - "/examples/layout/grid_and_list"
      - "/examples/layout/lakes/interactive"
      - "/examples/layout/lakes/step2"
      - "/examples/layout/lakes/step3"
      - "/examples/layout/lakes/step4"
      - "/examples/layout/lakes/step5"
      - "/examples/layout/lakes/step6"
      - "/examples/layout/non_material"
      - "/examples/layout/pavlova"
      - "/examples/layout/row_column"
      - "/examples/layout/sizing"
      - "/examples/perf/concurrency/isolates"
      - "/examples/perf/deferred_components"
      - "/examples/platform_integration/compose_activities"
      - "/examples/platform_integration/pigeon"
      - "/examples/platform_integration/platform_channels"
      - "/examples/platform_integration/platform_views"
      - "/examples/platform_integration/plugin_api_migration"
      - "/examples/resources/architectural_overview"
      - "/examples/resources/dart_swift_concurrency"
      - "/examples/state_mgmt/simple"
      - "/examples/testing/code_debugging"
      - "/examples/testing/common_errors"
      - "/examples/testing/errors"
      - "/examples/testing/integration_tests/how_to"
      - "/examples/testing/native_debugging"
      - "/examples/tools"
      - "/examples/ui/adaptive_app_demos"
      - "/examples/ui/advanced/actions_and_shortcuts"
      - "/examples/ui/advanced/focus"
      - "/examples/ui/assets_and_images"
      - "/examples/ui/interactive"
      - "/examples/ui/widgets_intro"
      - "/examples/visual_debugging"
