language: dart
dart: stable

# Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
# https://github.com/flutter/flutter/issues/6207
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - lib32stdc++6
      - libstdc++6

cache:
  timeout: 1000
  bundler: true
  directories:
  - $HOME/.pub-cache
  - $HOME/.nvm
  - $HOME/.rvm
  - node_modules

env:
  global:
    - JEKYLL_ENV=production
    - TZ=US/Pacific # normalize build timestamp
  matrix:
    - TASK="./tool/check-code.sh"
    - TASK="bundle exec jekyll build"

matrix: # temporarily allow this task to fail
  allow_failures:
    - env: TASK="./tool/check-code.sh"

before_install:
  - source ./tool/env-set.sh
  - ./tool/before-install.sh

install:
  - ./tool/install.sh
  # - ./tool/shared/write-ci-info.sh -v

script: $TASK

after_script:
  - if [[ $TASK == *build* ]]; then ./tool/shared/check-links.sh || travis_terminate 1; fi

deploy:
  - provider: script
    script: ./tool/shared/deploy.sh --robots ok default
    skip_cleanup: true
    on:
      repo: flutter/website
      branch: master
      condition: $TASK == *build* && $TRAVIS_EVENT_TYPE == push

# Only run Travis jobs for named branches (to avoid double builds for each PR)
branches:
  only: [master, /^\d\.x$/, /^\d-dev$/, /travis-build/]
