language: dart
dart: stable
os: linux
dist: xenial

# Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
# https://github.com/flutter/flutter/issues/6207
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - lib32stdc++6
      - libstdc++6

cache:
  timeout: 1000
  bundler: true
  directories:
  - $HOME/.pub-cache
  - $HOME/.nvm
  - $HOME/.rvm
  - node_modules

jobs:
  include:
    - name: "Submodule commit: code check"
      env:
        - TASK="./tool/check-code.sh"

    - name: "Submodule commit: jekyll build"
      env:
        - TASK="bundle exec jekyll build"

    - name: "Dev channel: code check"
      env:
        - TASK="./tool/check-code.sh"
        - CHANNEL=dev

    - name: "Dev channel: null safety code check"
      env:
        - TASK="./tool/check-code.sh --null-safety"
        - CHANNEL=dev

    - name: "Dev channel: jekyll build"
      env:
        - TASK="bundle exec jekyll build"
        - CHANNEL=dev

    - name: "Beta channel: code check"
      env:
        - TASK="./tool/check-code.sh"
        - CHANNEL=beta

    - name: "Beta channel: null safety code check"
      env:
        - TASK="./tool/check-code.sh --null-safety"
        - CHANNEL=beta

    - name: "Beta channel: jekyll build"
      env:
        - TASK="bundle exec jekyll build"
        - CHANNEL=beta

    - name: "Stable channel: code check"
      env:
        - TASK="./tool/check-code.sh"
        - CHANNEL=stable

    - name: "Stable channel: jekyll build"
      env:
        - TASK="bundle exec jekyll build"
        - CHANNEL=stable

  allow_failures:
    - name: "Submodule commit: code check"
    - name: "Submodule commit: jekyll build"
    - name: "Dev channel: code check"
    - name: "Dev channel: jekyll build"
    - name: "Beta channel: code check"
    - name: "Beta channel: jekyll build"

env:
  global:
    - JEKYLL_ENV=production
    - TZ=US/Pacific # normalize build timestamp

before_install:
  - source ./tool/env-set.sh
  - ./tool/before-install.sh
  - if [[ ! -z $CHANNEL ]]; then ./flutter/bin/flutter channel $CHANNEL; fi

install:
  - ./tool/install.sh

script: $TASK

after_script:
  - if [[ $TASK == *build* ]]; then ./tool/shared/check-links.sh || travis_terminate 1; fi

deploy:
  - provider: script
    script: ./tool/shared/deploy.sh --robots ok default
    skip_cleanup: true
    on:
      repo: flutter/website
      branch: master
      condition: $TASK == *build* && $TRAVIS_EVENT_TYPE == push

# Only run Travis jobs for named branches (to avoid double builds for each PR)
branches:
  only: [master, /^\d\.x$/, /^\d-dev$/, /travis-build/]
