# Site settings
title: Flutter
email: flutter-dev@googlegroups.com
email_name: flutter-dev@
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://flutter.io"
github_username: flutter

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

exclude: [example, packages, tool]
