title: Flutter

url: https://flutter.dev

email: flutter-dev@googlegroups.com

google_analytics_id: UA-67589403-1
google_site_verification: HFqxhSbf9YA_0rBglNLzDiWnrHiK_w4cqDh2YD2GEY4
google_tag_manager_id: GTM-ND4LWWZ
default_share_image: /assets/images/flutter-logo-sharing.png
  

branch: main

github_username: flutter
repo:
  organization: https://github.com/flutter

  this: https://github.com/flutter/website

  flutter: https://github.com/flutter/flutter
  samples: https://github.com/flutter/samples
  plugins: https://github.com/flutter/plugins
  gallery: https://github.com/flutter/gallery
dart:
  api: https://api.dart.dev
  sdk:
    channel: stable
sdk:
  channel: stable # When changing this value also update it in src/_assets/js/archive.js
social:
  twitter: https://twitter.com/FlutterDev
  youtube: https://www.youtube.com/flutterdev
dart-site: https://dart.dev
news: https://news.dartlang.org
api: https://api.flutter.dev
master-api: https://master-api.flutter.dev
pub: https://pub.dev
pub-api: https://pub.dev/documentation
pub-pkg: https://pub.dev/packages
flutter-medium: https://medium.com/flutter
medium: https://medium.com
dartpad: https://dartpad.dev
gallery: https://gallery.flutter.dev
material: https://material.io
so: https://stackoverflow.com
github: https://github.com
flutter-assets: https://flutter.github.io/assets-for-api-docs/assets
android-dev: https://developer.android.com
apple-dev: https://developer.apple.com
google-blog: https://developers.googleblog.com
developers: https://developers.google.com
codelabs: https://codelabs.developers.google.com
groups: https://groups.google.com
firebase: https://firebase.google.com
flutterfire: https://firebase.flutter.dev
youtube-site: https://youtube.com


########### Jekyll ###########

source: src
permalink: pretty
exclude: []
sass:
  sass_dir: _sass
  cache: false
  style: compressed
  load_paths:
    - ../node_modules

plugins:
  - jekyll-toc
toc:
  min_level: 2
  max_level: 4

defaults:
  - scope:
      path: assets/images
    values:
      image: true
  - scope:
      path: assets/js
    values:
      js: true
  - scope:
      path: ''
    values:
      layout: default
      show-nav-get-started-button: true
      show_banner: true
      show_footer: true
  - scope:
      path: 'docs'
    values:
      toc: true
  - scope:
      path: 'docs/cookbook'
    values:
      show_breadcrumbs: true
  - scope:
      path: 'docs/development'
    values:
      show_breadcrumbs: true
  - scope:
      path: 'docs/development/ui/widgets'
    values:
      toc: false
  - scope:
      path: 'docs/get-started'
    values:
      show_breadcrumbs: true
  - scope:
      path: 'docs/get-started/flutter-for'
    values:
      show_breadcrumbs: false


########### Alerts ###########
# TODO these are bootstrap related, will not be supported

alert:
  bonus: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    **Bonus questions!**
  important: >-
    <aside class="alert alert-warning" role="alert" markdown="1">
    <i class="fas fa-exclamation-circle"></i> **Important:**
  info: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <i class="fas fa-info-circle"></i>
  note: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <i class="fas fa-info-circle"></i> **Note:**
  version-note: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <i class="fas fa-code-branch"></i> **Version note:**
  secondary: >-
    <aside class="alert alert-secondary" role="alert" markdown="1">
  tip: >-
    <aside class="alert alert-success" role="alert" markdown="1">
    <i class="far fa-lightbulb"></i> **Tip:**
  warning: >-
    <aside class="alert alert-warning" role="alert" markdown="1">
    <i class="fas fa-exclamation-triangle"></i> **Warning:**
  end: </aside>


########### Custom ###########

custom:
  dartpad:
    embed-dart-prefix: https://dartpad.dev/embed-dart.html
    embed-flutter-prefix: https://dartpad.dev/embed-flutter.html
    embed-html-prefix: https://dartpad.dev/embed-html.html
    embed-inline-prefix: https://dartpad.dev/embed-inline.html
