name: flutter_io

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dev_dependencies:
  build_runner: ^0.10.1
  code_excerpt_updater: any
  code_excerpter: any
  linkcheck: ^2.0.6

dependency_overrides:
  code_excerpt_updater:
    git: https://github.com/chalin/code_excerpt_updater.git
    # path: ../code_excerpt_updater
  code_excerpter:
    git: https://github.com/chalin/code_excerpter.git
    # path: ../code_excerpter
