name: docs_flutter_dev
publish_to: none

environment:
  sdk: ^3.3.0

dev_dependencies:
  build_runner: ^2.4.8
  code_excerpt_updater:
    path: site-shared/packages/code_excerpt_updater
  code_excerpter:
    path: site-shared/packages/code_excerpter
  linkcheck: ^3.0.0
