name: flutter_io
version: 0.0.1
dev_dependencies:
  flutter:
    path: ../flutter/packages/flutter
  flutter_test:
    path: ../flutter/packages/flutter_test
  flutter_driver:
    path: ../flutter/packages/flutter_driver
  path: any
  test: ^0.12.0
