name: docs_flutter_dev_site
publish_to: none
homepage: https://docs.flutter.dev

resolution: workspace
environment:
  sdk: ^3.9.2

dependencies:
  build: ^4.0.2
  collection: ^1.19.1
  crypto: ^3.0.7
  html: ^0.15.6
  http: ^1.5.0
  jaspr: ^0.21.6
  jaspr_content: ^0.4.3
  # Used as our template engine.
  liquify: ^1.3.1
  markdown: ^7.3.0
  markdown_description_list: ^0.1.1
  meta: ^1.17.0
  # Used for syntax highlighting.
  opal: ^0.2.0
  path: ^1.9.1
  pub_semver: ^2.2.0
  universal_web: ^1.1.1+1

dev_dependencies:
  analysis_defaults:
    git:
      url: https://github.com/dart-lang/site-shared
      path: pkgs/analysis_defaults
      ref: f91ed8ecef6a0b31685804fe4102b25fda021460
  build_runner: ^2.10.1
  build_web_compilers: ^4.4.0
  jaspr_builder: ^0.21.6
  sass: ^1.93.3
  sass_builder: ^2.4.0

jaspr:
  mode: static
