name: mocking
description: Use the Mockito package to mimic the behavior of services for testing.

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  example_utils:
    path: ../../../../example_utils
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
