name: adaptive_app_demos
description: Demo code for adaptive app development techniques.
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  bitsdojo_window: ^0.1.6
  flextras: ^1.0.0
  provider: ^6.1.5
  universal_platform: ^1.1.0
  platform: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
