name: adaptive_app_demos
description: Demo code for adaptive app development techniques.
publish_to: none

environment:
  sdk: ^3.6.0-0

dependencies:
  flutter:
    sdk: flutter

  bitsdojo_window: ^0.1.6
  flextras: ^1.0.0
  provider: ^6.1.1
  universal_platform: ^1.0.0
  platform: ^3.1.4

dev_dependencies:
  example_utils:
    path: ../../example_utils
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
