name: games_services_example
description: Games services

resolution: workspace
environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  games_services: ^5.0.0
  logging: ^1.3.0

flutter:
  uses-material-design: true
