name: background_parsing
description: Background parsing

resolution: workspace
environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

flutter:
  uses-material-design: true
