name: firestore_multiplayer
description: Firestore multiplayer

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  async: ^2.13.0
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  logging: ^1.3.0
  provider: ^6.1.5

flutter:
  uses-material-design: true
