name: firestore_multiplayer
description: Firestore multiplayer

environment:
  sdk: ^3.6.0-0

dependencies:
  flutter:
    sdk: flutter

  async: ^2.11.0
  cloud_firestore: ^4.15.4
  firebase_core: ^2.25.4
  logging: ^1.2.0
  provider: ^6.1.1

dev_dependencies:
  example_utils:
    path: ../../../example_utils

flutter:
  uses-material-design: true
