name: json
description: Sample state management code.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.6.0-0

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  example_utils:
    path: ../../example_utils
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
