name: adaptive_app_demos
description: Demo code for adaptive app development techniques.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter

  bitsdojo_window: ^0.1.5
  flextras: ^1.0.0
  provider: ^6.0.5
  universal_platform: ^1.0.0
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
