name: scrolling
description: A new Flutter project.

environment:
  sdk: ^3.6.0-0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_test:
    sdk: flutter

dev_dependencies:
  example_utils:
    path: ../../../../example_utils

flutter:
  uses-material-design: true
