name: scrolling
description: A new Flutter project.

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  path: ^1.8.3
  flutter_test:
    sdk: flutter

dev_dependencies:
  example_utils:
    path: ../../../../example_utils

flutter:
  uses-material-design: true
