name: themes
description: Sample code for themes cookbook recipe.

resolution: workspace
environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^7.0.0

flutter:
  uses-material-design: true
