name: themes
description: Sample code for themes cookbook recipe.

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
