name: themes
description: Sample code for themes cookbook recipe.

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0

flutter:
  uses-material-design: true
