name: flutter_docs_examples
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - _animation/basic_hero_animation
  - _animation/basic_radial_hero_animation
  - _animation/basic_staggered_animation
  - _animation/hero_animation
  - _animation/radial_hero_animation
  - _animation/radial_hero_animation_animate_rectclip
  - _animation/staggered_pic_selection
  - accessibility
  - animation/animate0
  - animation/animate1
  - animation/animate2
  - animation/animate3
  - animation/animate4
  - animation/animate5
  - app-architecture/command
  - app-architecture/offline_first
  - app-architecture/optimistic_state
  - app-architecture/result
  - app-architecture/todo_data_service
  - cookbook/animation/animated_container
  - cookbook/animation/opacity_animation
  - cookbook/animation/page_route_animation
  - cookbook/animation/physics_simulation
  - cookbook/design/drawer
  - cookbook/design/fonts
  - cookbook/design/orientation
  - cookbook/design/package_fonts
  - cookbook/design/snackbars
  - cookbook/design/tabs
  - cookbook/design/themes
  - cookbook/effects/download_button
  - cookbook/effects/drag_a_widget
  - cookbook/effects/expandable_fab
  - cookbook/effects/gradient_bubbles
  - cookbook/effects/nested_nav
  - cookbook/effects/parallax_scrolling
  - cookbook/effects/shimmer_loading
  - cookbook/effects/staggered_menu_animation
  - cookbook/effects/typing_indicator
  - cookbook/forms/focus
  - cookbook/forms/retrieve_input
  - cookbook/forms/text_field_changes
  - cookbook/forms/text_input
  - cookbook/forms/validation
  - cookbook/games/achievements_leaderboards
  - cookbook/games/firestore_multiplayer
  - cookbook/gestures/dismissible
  - cookbook/gestures/handling_taps
  - cookbook/gestures/ripples
  - cookbook/images/cached_images
  - cookbook/images/fading_in_images
  - cookbook/images/network_image
  - cookbook/lists/basic_list
  - cookbook/lists/floating_app_bar
  - cookbook/lists/grid_lists
  - cookbook/lists/horizontal_list
  - cookbook/lists/long_lists
  - cookbook/lists/mixed_list
  - cookbook/lists/spaced_items
  - cookbook/maintenance/error_reporting
  - cookbook/navigation/hero_animations
  - cookbook/navigation/named_routes
  - cookbook/navigation/navigate_with_arguments
  - cookbook/navigation/navigation_basics
  - cookbook/navigation/passing_data
  - cookbook/navigation/returning_data
  - cookbook/networking/authenticated_requests
  - cookbook/networking/background_parsing
  - cookbook/networking/delete_data
  - cookbook/networking/fetch_data
  - cookbook/networking/send_data
  - cookbook/networking/update_data
  - cookbook/networking/web_sockets
  - cookbook/persistence/key_value
  - cookbook/persistence/reading_writing_files
  - cookbook/persistence/sqlite
  - cookbook/plugins/google_mobile_ads
  - cookbook/plugins/picture_using_camera
  - cookbook/plugins/play_video
  - cookbook/testing/integration/introduction
  - cookbook/testing/integration/profiling
  - cookbook/testing/unit/counter_app
  - cookbook/testing/unit/mocking
  - cookbook/testing/widget/finders
  - cookbook/testing/widget/introduction
  - cookbook/testing/widget/orientation_tests
  - cookbook/testing/widget/scrolling
  - cookbook/testing/widget/tap_drag
  - data-and-backend/json
  - deployment/obfuscate
  - get-started/flutter-for/android_devs
  - get-started/flutter-for/declarative
  - get-started/flutter-for/ios_devs
  - get-started/flutter-for/react_native_devs
  - get-started/flutter-for/web_devs
  - get-started/flutter-for/xamarin_devs
  - googleapis
  - integration_test
  - integration_test_migration
  - internationalization/add_language
  - internationalization/gen_l10n_example
  - internationalization/intl_example
  - internationalization/minimal
  - layout/base
  - layout/card_and_stack
  - layout/constraints
  - layout/container
  - layout/gallery
  - layout/grid_and_list
  - layout/lakes/interactive
  - layout/lakes/step2
  - layout/lakes/step3
  - layout/lakes/step4
  - layout/lakes/step5
  - layout/lakes/step6
  - layout/non_material
  - layout/pavlova
  - layout/row_column
  - layout/sizing
  - perf/concurrency/isolates
  - perf/deferred_components
  - platform_integration/compose_activities
  - platform_integration/pigeon
  - platform_integration/platform_channels
  - platform_integration/platform_views
  - platform_integration/plugin_api_migration
  - resources/architectural_overview
  - resources/dart_swift_concurrency
  - state_mgmt/simple
  - testing/code_debugging
  - testing/common_errors
  - testing/errors
  - testing/integration_tests/how_to
  - testing/native_debugging
  - tools
  - ui/actions_and_shortcuts
  - ui/adaptive_app_demos
  - ui/assets_and_images
  - ui/focus
  - ui/interactive
  - ui/navigation
  - ui/widgets_intro
  - visual_debugging

dev_dependencies:
  flutter_lints: ^6.0.0
