name: counter_app
description: Flutter project for unit testing introduction.

publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  test: ^1.24.9

dev_dependencies:
  example_utils:
    path: ../../../../example_utils

flutter:
  uses-material-design: true
