name: actions_and_shortcuts
description: Sample actions and shortcuts code.
publish_to: none

environment:
  sdk: ^3.6.0-0

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  example_utils:
    path: ../../../example_utils

flutter:
  uses-material-design: true
