name: firebase_backend_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.2.0

dependencies:
  googleapis: ^11.0.0
  googleapis_auth: ^1.3.0
  http: ^1.1.0
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  app_store_server_sdk: ^1.2.5

dev_dependencies:
  lints: ">=2.0.0 <4.0.0"
  test: ^1.16.0
