name: google_sign_in_example
publish_to: none

environment:
  sdk: ^3.6.0-0

dependencies:
  collection: any # Pull the version of collection from Flutter.
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  http: ^1.2.0

dev_dependencies:
  example_utils:
    path: ../example_utils
