name: google_sign_in_example
publish_to: none

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  collection: ^1.15.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.2
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.2
  googleapis: ^9.1.0
  http: ^0.13.0

dev_dependencies:
  flutter_lints: ^2.0.1
