name: google_sign_in_example
publish_to: none

environment:
  sdk: ^3.0.3

dependencies:
  collection: ^1.15.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.2
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.1
  googleapis: ^11.0.0
  http: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
