name: google_sign_in_example
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0-0

dependencies:
  collection: any # Pull the version of package:collection from Flutter.
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0
  http: ^1.5.0
