name: gen_l10n_example
description: Example of an internationalized Flutter app that uses `flutter gen-l10n`

environment:
  sdk: ^3.0.3

# #docregion FlutterLocalizations
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
# #enddocregion FlutterLocalizations

dev_dependencies:
  flutter_lints: ^2.0.1

# #docregion Generate
# The following section is specific to Flutter.
flutter:
  generate: true # Add this line
# #enddocregion Generate
  uses-material-design: true
