name: inject_dartpad
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  html_unescape: ^2.0.0
  web: ^0.5.1

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  path: ^1.9.0
  test: ^1.25.2
  webdev: any
