name: key_value
description: Key value

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  flutter_test:
    sdk: flutter

dev_dependencies:
  example_utils:
    path: ../../../example_utils

flutter:
  uses-material-design: true
