name: key_value
publish_to: none
description: >-
  Examples and code excerpts for a cookbook recipe that
  shows how to use the shared_preferences package.

environment:
  sdk: ^3.6.0-0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_test:
    sdk: flutter

dev_dependencies:
  example_utils:
    path: ../../../example_utils

flutter:
  uses-material-design: true
