name: json
description: Sample state management code.

version: 1.0.0+1

environment:
  sdk: ^3.1.0-0

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.2
