name: json
description: Sample state management code.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
