name: grid
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/pic1.jpg
    - images/pic2.jpg
    - images/pic3.jpg
    - images/pic4.jpg
    - images/pic5.jpg
    - images/pic6.jpg
    - images/pic7.jpg
    - images/pic8.jpg
    - images/pic9.jpg
    - images/pic10.jpg
    - images/pic11.jpg
    - images/pic12.jpg
    - images/pic13.jpg
    - images/pic14.jpg
    - images/pic15.jpg
    - images/pic16.jpg
    - images/pic17.jpg
    - images/pic18.jpg
    - images/pic19.jpg
    - images/pic20.jpg
    - images/pic21.jpg
    - images/pic22.jpg
    - images/pic23.jpg
    - images/pic24.jpg
    - images/pic25.jpg
    - images/pic26.jpg
    - images/pic27.jpg
    - images/pic28.jpg
    - images/pic29.jpg


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
# flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  # uses-material-design: true

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
