name: dart_tools
description: Dart-based tools for flutter/website.
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  logging: ^1.2.0
  path: ^1.8.3

dev_dependencies:
  analysis_defaults:
    path: ../../site-shared/packages/analysis_defaults
