name: text_field_changes
description: Sample code for text_field_changes

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true
