name: handling_taps
description: Example on handling_taps cookbook recipe.

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true
